### ISSUE TITLE
Replacing default tabs

### ISSUE THREAD

**Issue by fredrikaverpil** [FabianWirth/search.nvim#12]
Hi 👋 and thanks for nice very nice plugin!

I would like to replace the default tabs like so:

- Files: nvim-telescope/telescope-fzf-native.nvim
- Grep: nvim-telescope/telescope-live-grep-args.nvim

One way is I simply overwrite the `tabs` config:

```lua
{
  "FabianWirth/search.nvim",
  dependencies = {
    "nvim-telescope/telescope.nvim",
  },
  opts = {
    tabs = {
      {
        name = ...
        tele_func = ...
        available = ...
      },
    },
  },
},
```

Would you recommend me doing this, or do you think the settings can support this via some specific opts variable?

**Comment by FabianWirth** [comment]
happy to hear you like the plugin :tada: 
it's possible and intended to use `tabs` key in the options for setting up the plugin! It's just missing from the README at the moment, but i'll add it to the refactor at #11
