### ISSUE TITLE
Passing telescope-options when calling search.

### ISSUE THREAD

**Issue by messatsuu** [FabianWirth/search.nvim#18]
How do I pass the options that the telescope picker would use for my custom tabs? 
Consider I have a tab with the following options:
  
```lua
{
    "Files",
     function(opts)
        opts = opts or {}
        telescope_builtin.find_files(opts)
    end
},
```
The snippet has the variable `opts` that get passed to the picker. How do I pass those when calling search.nvim from e.g. a hotkey:
```lua
require('search').open({ tab_name = 'Files' })
```
Something like this?
```lua
require('search').open({ tab_name = 'Files', opts = { default_text = "default" } })
```

Also, is there a way to have search.nvim opened again when using `telescope.resume()`?

**Comment by Ev-1** [comment]
As far as I can tell from the code you can't currently pass options like that. Depending on your use case though you could maybe get away with passing options directly like this.
```lua
          tabs = {
            { name = "Files", tele_func = function() telescope.find_files({ gitignore = true, default_text = visual_selection() }) end },
            { name = "Buffers",  tele_func = telescope.buffers },
          },
```
I do this to allow me to search for the currently highlighted text, if I am in visual mode.

This doesn't allow you to pass different options for different key binds though. But I guess if you really want that you could use multiple collections with different settings and bind them to different key binds, until something like you showed is implemented.

The second question I'm not sure about.

**Comment by Ev-1** [comment]
Hello @messatsuu 

I made a branch that implements what I think you wanted from the argument passing. If you're still using the plugin it would be cool if you checked it out to see if it works as you wanted.

**Comment by messatsuu** [comment]
Thank you soo much!
I've continued to use the plugin and am more than happy to see this change implemented!!

Edit: The Branch works flawlessly!
