### ISSUE TITLE
preview cuts off tabline

### ISSUE THREAD

**Issue by yingzhu146** [FabianWirth/search.nvim#7]
![20231210-124158](https://github.com/FabianWirth/search.nvim/assets/59233975/999886b2-87a1-4d52-bbb5-c1522d19cb57)
![20231210-124202](https://github.com/FabianWirth/search.nvim/assets/59233975/3352adb0-3059-4aaf-839e-42dc4f2aba28)
it seems that the preview cuts of the tabline - you can see with preview a lot less tabs are shown even though there would be space.

also very fun idea since I'm running out of space for all my pickers: how about mulitple rows/cols and navigating with hjkl or something? 😂

Thanks a ton 🙏

**Comment by FabianWirth** [comment]
I'll try to fix the hide-behind-results situation 😁

Stacking the tabs sounds good.. but I'd keep the keybindings opt-in since I feel like C-jklh are usually used otherwise in the telescope environment.. 

At least adding a 'per_row' in the configs should be easy 👍🏻
