### ISSUE TITLE
question: how to protect from failing pickers

### ISSUE THREAD

**Issue by yingzhu146** [FabianWirth/search.nvim#8]
pickers like these will fail regularly
```lua
local function is_git()
  return vim.fn.isdirectory(".git") == 1
end

{
  name = "octo issues",
  tele_func = function()
    pcall(require("telescope").extensions.octo.issues)
  end,
  available = is_git,
},
```
however, octo.nvim doesn't expose an easy way for me to check if there are issues without deeply understanding octo code. This is the case for many other pickers as well.

Preferrably, there would be a mechanism to continue cycling through as if a picker isn't available if loading failed.

Right now, whenever I get to the octo tab, it'll crash search.nvim.

Thanks a lot 🙏

**Comment by FabianWirth** [comment]
the call to the telescope function is already wrapped in a pcall - but there is no error handling yet 😅 cycling to the next window sounds good tho 👍

**Comment by FabianWirth** [comment]
You can check out the 'refactor' branch where failing pickers don't cause the search tabs to exit. However, for 'octo,' the current behavior is that the search tabs will wait for 'octo' to appear. Until now, I haven't found a way to interrupt the startup of 'octo' if it takes longer than a specific time (like when holding down the tab key).

If the picker throws an error that is caught by 'pcall,' the tab is skipped.
```lua
--- for example
function() error("some error") end
```

Do you have other failing pickers for me to test? The behavior of throwing an error and 'octo' is very different, and I am not quite sure why.

**Comment by yingzhu146** [comment]
Amazing, works like a charm!

Maybe you can try something via timer?


```lua

local function timeout_function(func, timeout)
  local timer = vim.loop.new_timer()
  local done = false
  local result = nil

  -- Start the timer
  timer:start(timeout, 0, vim.schedule_wrap(function()
    if not done then
      timer:stop()
      timer:close()
      error('Function timed out')
    end
  end))

  -- Call the function
  result = func()

  -- Stop the timer
  done = true
  timer:stop()
  timer:close()

  return result
end

-- Usage:
local function long_running_function()
  -- This function takes a long time to complete
end

local result = timeout_function(long_running_function, 200)
```

**Comment by FabianWirth** [comment]
i tried using the timer, but the issue (especially with octo) is, that even if the the timer closes the function will not terminate.. for `dap` - if used without an available function, the error handling seems to work :+1:
